/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Ug5mQM2iRov
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client';

import React from "react";
import Link from "next/link";
import { useInView } from 'react-intersection-observer';
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator } from "@/components/ui/dropdown-menu";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import Goldimage from '../ui/Gold_desk.png';
export function Golden_Landing() {
  const [ref1, inView1] = useInView({ threshold: 0.6, triggerOnce: true });
const [ref2, inView2] = useInView({ threshold: 0.6,triggerOnce: true  });
const [ref3, inView3] = useInView({ threshold: 0.6,triggerOnce: true });
const [ref4, inView4] = useInView({ threshold: 0.6,triggerOnce: true });
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header
        className="sticky top-0 z-50 flex items-center justify-between h-9 px-4 md:px-6 border-b bg-primary text-primary-foreground  md:py-12">
        <nav className=" md:flex gap-4 sm:gap-6">
          <Link href="../" className="flex items-center gap-2" >
            <CarIcon className="w-6 h-6 " />
            <span className="text-lg font-semibold hover:text-primary-foreground transition-colors">Renta</span>
          </Link>
          <div className="hidden md:flex items-center gap-4">
            <Link
              href="/Search"
              className="text-muted-foreground hover:text-primary-foreground transition-colors"
              >
              Search
            </Link>
            <Link
              href="/Rating_Reviews"
              className="text-muted-foreground hover:text-primary-foreground transition-colors"
              >
              Ratings & Reviews
            </Link>
            <Link
              href="/Bookingdetail"
              className="text-muted-foreground hover:text-primary-foreground transition-colors"
              >
              My Bookings
            </Link>
            <Link
              href="/Accessibility"
              className="text-muted-foreground hover:text-primary-foreground px-3 py-2 rounded-md transition-colors"
              >
              Accessibility
            </Link>
            
          </div>
        </nav>
        <div className="flex items-center gap-4">
        <DropdownMenu>
              <DropdownMenuTrigger
                className="flex items-center gap-1 text-muted-foreground  hover:text-primary-foreground transition-colors">
                <span>Language</span>
                <ChevronDownIcon className="h-4 w-4" />
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem>
                  <Link href="#" className="flex items-center gap-2" >
                    <FlagIcon className="h-4 w-4" />
                    <span>Türkçe</span>
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Link href="#" className="flex items-center gap-2" >
                    <FlagIcon className="h-4 w-4" />
                    <span>English</span>
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Link href="#" className="flex items-center gap-2" >
                    <FlagIcon className="h-4 w-4" />
                    <span>العربية</span>
                  </Link>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Avatar className="h-6 w-6 rounded-lg">
                  <AvatarImage src="/placeholder-user.jpg" className="rounded-xl" />
                  <AvatarFallback>JP</AvatarFallback>
                  <span className="sr-only">Toggle user menu</span>
                </Avatar>
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuItem><Link href="/User_Account">My Account</Link></DropdownMenuItem>
                <DropdownMenuItem><Link href='/Settings'>Settings</Link></DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem><Link href='/Login'>Logout</Link></DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
      </header>
      <main className="flex-1 " style={{
  backgroundImage: `url(${Goldimage.src})`,
  backgroundRepeat: 'no-repeat',
  backgroundSize: 'cover',
  backgroundAttachment: 'fixed',
  backgroundPosition: 'center'
}}>
        <section
           ref={ref1}
           className={`w-full py-12 md:py-24 lg:py-32 bg-background/10 ${
            inView1 ? 'animate-fadeInUp' : 'opacity-0'
           }`}>
          <div className="container px-4 md:px-6">
            <div
              className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1
                    className="text-3xl font-bold tracking-tighter text-primary-foreground sm:text-5xl xl:text-6xl/none">
                    Sign up today and experience luxury
                  </h1>
                  <p className="max-w-[600px] text-primary-foreground md:text-xl">
                    Unlock exclusive perks, premium vehicles, and personalized service with our Golden Membership.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link href='/Golden/GoldenHome'><Button
                    className="inline-flex h-10 items-center justify-center rounded-md px-8 text-sm font-medium shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50">
                    Sign Up Now
                  </Button></Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section  ref={ref2}
          className={`w-full py-12 md:py-24 lg:py-32 bg-background/10 ${
            inView2 ? 'animate-fadeInUp' : 'opacity-0'
          }`}>
          <div className="container px-4 md:px-6">
            <div className="grid gap-10 sm:px-10 md:gap-16 md:grid-cols-2">
              <div className="space-y-4">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Exclusive Perks</div>
                <h2
                  className="lg:leading-tighter text-3xl font-bold text-primary-foreground tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Elevate Your Rental Experience
                </h2>
                <ul className="space-y-2 text-primary-foreground">
                  <li className="flex items-center gap-2">
                    <CheckIcon className="h-5 w-5 text-primary-foreground" />
                    Priority vehicle selection
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckIcon className="h-5 w-5 text-primary-foreground" />
                    Complimentary upgrades
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckIcon className="h-5 w-5 text-primary-foreground" />
                    Dedicated concierge service
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckIcon className="h-5 w-5 text-primary-foreground" />
                    Exclusive member events
                  </li>
                </ul>
              </div>
              <div className="flex flex-col items-start space-y-4">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Premium Vehicles</div>
                <p
                  className="mx-auto max-w-[700px] text-primary-foreground md:text-xl/relaxed">
                  Experience the ultimate in luxury and performance with our exclusive fleet of premium vehicles,
                  including the latest models from top brands.
                </p>
                <Link
                  href="#"
                  className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}>
                  View Our Fleet
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section  ref={ref3}
          className={`w-full py-12 md:py-24 lg:py-32 bg-background/10 ${
            inView3 ? 'animate-fadeInUp' : 'opacity-0'
          }`}>
          <div className="container px-4 md:px-6">
            <div className="grid gap-10 sm:px-10 md:gap-16 md:grid-cols-2">
              <div className="space-y-4">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Personalized Service</div>
                <h2
                  className="lg:leading-tighter text-3xl font-bold tracking-tighter text-primary-foreground sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Your Rental, Your Way
                </h2>
                <ul className="space-y-2 text-primary-foreground">
                  <li className="flex items-center gap-2">
                    <CheckIcon className="h-5 w-5 text-primary-foreground" />
                    Dedicated account manager
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckIcon className="h-5 w-5 text-primary-foreground" />
                    Customized rental packages
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckIcon className="h-5 w-5 text-primary-foreground" />
                    Flexible booking and return
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckIcon className="h-5 w-5 text-primary-foreground" />
                    Seamless 24/7 support
                  </li>
                </ul>
              </div>
              <div className="flex flex-col items-start space-y-4">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Luxury Lifestyle</div>
                <p
                  className="mx-auto max-w-[700px] text-primary-foreground md:text-xl/relaxed">
                  Indulge in the finer things in life with our Golden Membership. From exclusive events to personalized
                  concierge services, we cater to your every need.
                </p>
                <Link
                  href="#"
                  className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}>
                  Learn More
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section
           ref={ref4}
           className={`w-full py-12 md:py-24 lg:py-32 bg-background/10 ${
             inView4 ? 'animate-fadeInUp' : 'opacity-0'
           }`}>
          <div className="container px-4 md:px-6">
            <div
              className="grid items-center justify-center gap-4 px-4 text-center md:px-6">
              <div className="space-y-3">
                <h2
                  className="text-3xl font-bold tracking-tighter text-primary-foreground md:text-4xl/tight">
                  Elevate Your Rental Experience
                </h2>
                <p
                  className="mx-auto max-w-[600px] text-primary-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Join our Golden Membership and unlock a world of exclusive perks, premium vehicles, and personalized
                  service.
                </p>
              </div>
              <div className="mx-auto w-full max-w-sm space-y-2">
                <Button
                  className="inline-flex h-10 items-center justify-center rounded-md px-8 text-sm font-medium shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50">
                  Sign Up Now
                </Button>
                <p className="text-xs text-primary-foreground">
                  Membership is subject to approval.{" "}
                  <Link href="#" className="underline underline-offset-2" prefetch={false}>
                    Terms &amp; Conditions
                  </Link>
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer
        className="flex items-center justify-between h-fit px-4 md:px-6 border-b bg-primary text-primary-foreground py-6 md:py-12 ">
          <div className="container max-w-7xl grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-8 text-sm">
        <div className="grid gap-1">
          <h3 className="font-semibold">Company</h3>
          <Link href="#"  className=" hover:text-muted-foreground  rounded-md transition-colors">
            About Us
          </Link>
          <Link href="#"  className=" hover:text-muted-foreground  rounded-md transition-colors">
            Our Team
          </Link>
          <Link href="#"  className=" hover:text-muted-foreground  rounded-md transition-colors">
            Careers
          </Link>
        </div>
        <div className="grid gap-1">
          <h3 className="font-semibold">Products</h3>
          <Link href="#"  className=" hover:text-muted-foreground  rounded-md transition-colors">
            Cars
          </Link>
          <Link href="#"  className=" hover:text-muted-foreground  rounded-md transition-colors">
            Vans
          </Link>
          <Link href="#"  className=" hover:text-muted-foreground  rounded-md transition-colors">
            Accessibilty Vehicles
          </Link>
          
        </div>
        <div className="grid gap-1">
          <h3 className="font-semibold">Resources</h3>
          <Link href="#" prefetch={false } className=" hover:text-muted-foreground  rounded-md transition-colors">
            FAQ
          </Link>
          <Link href="#"  className=" hover:text-muted-foreground  rounded-md transition-colors">
            Ratings and reviews
          </Link>
          <Link href="#"  className=" hover:text-muted-foreground  rounded-md transition-colors">
            Support
          </Link>
        </div>
        <div className="grid gap-1">
          <h3 className="font-semibold">Legal</h3>
          <Link href="#"  className=" hover:text-muted-foreground  rounded-md transition-colors">
            Privacy Policy
          </Link>
          <Link href="#"  className=" hover:text-muted-foreground  rounded-md transition-colors">
            Terms of Service
          </Link>
          <Link href="#"  className=" hover:text-muted-foreground  rounded-md transition-colors">
            Cookie Policy
          </Link>
        </div>
        
      </div><h3 className="absolute right-5"> &#169;2024 Renta, Rent A Car Services</h3>
        </footer>
    </div>)
  );
}

function CarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2" />
      <circle cx="7" cy="17" r="2" />
      <path d="M9 17h6" />
      <circle cx="17" cy="17" r="2" />
    </svg>)
  );
}


function CheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M20 6 9 17l-5-5" />
    </svg>)
  );
}
function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}
function FlagIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>)
  );
}
