/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/atKuJMufHWT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator } from "@/components/ui/dropdown-menu"

export function User_page() {
  return (
    (<div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 w-screen items-left h-[8vh] ">
        <div className="max-w-4xl  flex items-left justify-between">
          <div className="flex items-left gap-4">
            <Avatar className="w-12 h-12 border rounded-lg">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <h1 className="text-2xl font-bold">Your <Link href="/" className="hover:underline hover:text-customyello transition-colors duration-300 ease-in-out">Renta</Link> Account</h1>
          </div>
          
        </div>
      </header>
      <div className="flex flex-row h-[92vh]">
      <aside
        className="flex flex-col items-left justify-between  w-fit px-4 md:px-6 border-b bg-primary text-primary-foreground py-2 md:py-12">
        <nav className="flex flex-col items-left justify-between h-fit w-fit  gap-4 sm:gap-6">
          <div className="flex flex-col md:flex items-left gap-4 w-fit">
            <Link
              href="#"
              className="text-background drop-shadow-glow hover:text-customyello transition-colors"
              prefetch={false}>
              Account Details
            </Link>
            <Link
              href="/User_Account/User_Rev"
              className="text-muted-foreground hover:text-customyello transition-colors"
              prefetch={false}>
              My Ratings & Reviews
            </Link>
            <Link
              href="#"
              className="text-muted-foreground hover:text-customyello transition-colors"
              prefetch={false}>
              Previous Bookings
            </Link>
            
          </div>
        </nav>
      
      </aside>
      <main className="flex-1 bg-background py-8 px-4 sm:px-6 lg:px-8">
        <div className="max-w-screen mx-auto grid grid-rows-2 sm:grid-rows-2 gap-6">
          <Card className="bg-primary text-primary-foreground">
            <CardHeader>
              <CardTitle>Personal Information</CardTitle>
            </CardHeader>
            <CardContent className="flex flex-row w-full justify-between">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 w-full justify-between">
                <div className="grid gap-2">
                  <Label className="text-primary-foreground">Full Name</Label>
                  <div>John Doe</div>
                </div>
                <div className="grid gap-2">
                  <Label className="text-primary-foreground">Date of Birth</Label>
                  <div>1985-06-15</div>
                </div>
                <div className="grid gap-2">
                  <Label className="text-primary-foreground">Driver&apos;s License:</Label>
                  <div>ABC123456</div>
                </div>
                <div className="grid gap-2">
                  <Label className="text-primary-foreground">Nationality</Label>
                  <div>United States</div>
                </div>
              </div><Button variant="outline" size="sm" className="text-secondary-foreground">
            Edit
          </Button>
            </CardContent>
          </Card>
          <Card className="bg-muted text-secondary-foreground">
            <CardHeader>
              <CardTitle>Contact Information</CardTitle>
            </CardHeader>
            <CardContent className="flex flex-row w-full justify-between">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 w-full justify-between">
                <div className="grid gap-2">
                  <Label className="text-secondary-foreground">Email</Label>
                  <div>john.doe@example.com</div>
                </div>
                <div className="grid gap-2">
                  <Label className="text-secondary-foreground">Phone</Label>
                  <div>+1 (555) 123-4567</div>
                </div>
                <div className="grid gap-2">
                  <Label className="text-secondary-foreground">Username</Label>
                  <div>jdoe</div>
                </div>
              </div><Button variant="outline" size="sm" className="bg-primary text-primary-foreground hover:bg-customgrey hover:text-primary-foreground ">
            Edit
          </Button>
            </CardContent>
          </Card>
        </div>
      </main>
    </div></div>)
  );
}
function CarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2" />
      <circle cx="7" cy="17" r="2" />
      <path d="M9 17h6" />
      <circle cx="17" cy="17" r="2" />
    </svg>)
  );
}
function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}

function FlagIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>)
  );
}